name: Issue Label Automation

on:
  issues:
    types:
      - closed

env:
  PROJECT_NAME: Roadmap

jobs:
  issue_labels:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Remove Priority and Task labels
        if: "github.event.action == 'closed'"
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: "⚠️優先度：高,🔥優先度：中,💐優先度：低,🍡タスク"
          repo-token: ${{ secrets.GHPROJECT_TOKEN }}
